//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komodex.DACP.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedDACPStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedDACPStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komodex.DACP.Localization.LocalizedDACPStrings", typeof(LocalizedDACPStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp; others.
        /// </summary>
        internal static string GeniusMixAndOthers {
            get {
                return ResourceManager.GetString("GeniusMixAndOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        internal static string MultipleItems {
            get {
                return ResourceManager.GetString("MultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item.
        /// </summary>
        internal static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string PlayStatusPaused {
            get {
                return ResourceManager.GetString("PlayStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing.
        /// </summary>
        internal static string PlayStatusPlaying {
            get {
                return ResourceManager.GetString("PlayStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string PlayStatusStopped {
            get {
                return ResourceManager.GetString("PlayStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streaming.
        /// </summary>
        internal static string PlayStatusStreaming {
            get {
                return ResourceManager.GetString("PlayStatusStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episodes.
        /// </summary>
        internal static string PodcastEpisodes {
            get {
                return ResourceManager.GetString("PodcastEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        internal static string SearchResultsAlbums {
            get {
                return ResourceManager.GetString("SearchResultsAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        internal static string SearchResultsArtists {
            get {
                return ResourceManager.GetString("SearchResultsArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies.
        /// </summary>
        internal static string SearchResultsMovies {
            get {
                return ResourceManager.GetString("SearchResultsMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcasts.
        /// </summary>
        internal static string SearchResultsPodcasts {
            get {
                return ResourceManager.GetString("SearchResultsPodcasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        internal static string SearchResultsSongs {
            get {
                return ResourceManager.GetString("SearchResultsSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episodes.
        /// </summary>
        internal static string TVShowEpisodes {
            get {
                return ResourceManager.GetString("TVShowEpisodes", resourceCulture);
            }
        }
    }
}
