//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komodex.WP7DACPRemote.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komodex.WP7DACPRemote.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Information.
        /// </summary>
        public static string AboutLibraryInformation {
            get {
                return ResourceManager.GetString("AboutLibraryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddAppBarButton {
            get {
                return ResourceManager.GetString("AddAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library.
        /// </summary>
        public static string AddLibraryButton {
            get {
                return ResourceManager.GetString("AddLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pair this device with a new library, download the Pairing Utility from our website:.
        /// </summary>
        public static string AddNewLibraryPageDescription {
            get {
                return ResourceManager.GetString("AddNewLibraryPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW LIBRARY.
        /// </summary>
        public static string AddNewLibraryPageTitle {
            get {
                return ResourceManager.GetString("AddNewLibraryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string BrowseLibraryAppBarButton {
            get {
                return ResourceManager.GetString("BrowseLibraryAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse library.
        /// </summary>
        public static string BrowseLibraryButton {
            get {
                return ResourceManager.GetString("BrowseLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelAppBarButton {
            get {
                return ResourceManager.GetString("CancelAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Library....
        /// </summary>
        public static string ChooseLibraryButton {
            get {
                return ResourceManager.GetString("ChooseLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose library.
        /// </summary>
        public static string ChooseLibraryMenuItem {
            get {
                return ResourceManager.GetString("ChooseLibraryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose library.
        /// </summary>
        public static string ChooseLibraryPageTitle {
            get {
                return ResourceManager.GetString("ChooseLibraryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Contact us] for support and feedback.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pair with iTunes or another compatible application for the first time, run the Pairing Utility on your computer.  This utility can be downloaded from our website at:.
        /// </summary>
        public static string FirstRunIntro1 {
            get {
                return ResourceManager.GetString("FirstRunIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When pairing has been completed, tap &quot;Add Library&quot; below to connect to your library..
        /// </summary>
        public static string FirstRunIntro2 {
            get {
                return ResourceManager.GetString("FirstRunIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be necessary for your phone to be connected to a Wi-fi network to continue..
        /// </summary>
        public static string FirstRunIntro3 {
            get {
                return ResourceManager.GetString("FirstRunIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow [@WP7Remote] on Twitter.
        /// </summary>
        public static string FollowOnTwitter {
            get {
                return ResourceManager.GetString("FollowOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone 7.
        /// </summary>
        public static string ForWP7 {
            get {
                return ResourceManager.GetString("ForWP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last connection attempt.
        /// </summary>
        public static string FromLastConnectionAttempt {
            get {
                return ResourceManager.GetString("FromLastConnectionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the library. Please make sure your phone is connected to the correct Wi-fi network and check the value entered in the hostname field..
        /// </summary>
        public static string LibraryConnectionErrorBody {
            get {
                return ResourceManager.GetString("LibraryConnectionErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string LibraryConnectionErrorTitle {
            get {
                return ResourceManager.GetString("LibraryConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please check your library and try again..
        /// </summary>
        public static string LibraryErrorBody {
            get {
                return ResourceManager.GetString("LibraryErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Error.
        /// </summary>
        public static string LibraryErrorTitle {
            get {
                return ResourceManager.GetString("LibraryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string LibraryHostname {
            get {
                return ResourceManager.GetString("LibraryHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string LibraryPIN {
            get {
                return ResourceManager.GetString("LibraryPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the library. Please check the PIN and try again..
        /// </summary>
        public static string LibraryPINErrorBody {
            get {
                return ResourceManager.GetString("LibraryPINErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Error.
        /// </summary>
        public static string LibraryPINErrorTitle {
            get {
                return ResourceManager.GetString("LibraryPINErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to your library. Please disconnect the USB cable between your phone and computer and try again..
        /// </summary>
        public static string LibraryUSBErrorBody {
            get {
                return ResourceManager.GetString("LibraryUSBErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connection Error.
        /// </summary>
        public static string LibraryUSBErrorTitle {
            get {
                return ResourceManager.GetString("LibraryUSBErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application currently requires iTunes version 10.1 or later. Please upgrade to the latest version of iTunes to continue..
        /// </summary>
        public static string LibraryVersionErrorBody {
            get {
                return ResourceManager.GetString("LibraryVersionErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Version Error.
        /// </summary>
        public static string LibraryVersionErrorTitle {
            get {
                return ResourceManager.GetString("LibraryVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure your phone is connected to a Wi-fi network and try again..
        /// </summary>
        public static string LibraryWifiErrorBody {
            get {
                return ResourceManager.GetString("LibraryWifiErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-fi Connection Error.
        /// </summary>
        public static string LibraryWifiErrorTitle {
            get {
                return ResourceManager.GetString("LibraryWifiErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string NextAppBarButton {
            get {
                return ResourceManager.GetString("NextAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingAppBarButton {
            get {
                return ResourceManager.GetString("NowPlayingAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingButton {
            get {
                return ResourceManager.GetString("NowPlayingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play/pause.
        /// </summary>
        public static string PlayPauseAppBarButton {
            get {
                return ResourceManager.GetString("PlayPauseAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string PreviousAppBarButton {
            get {
                return ResourceManager.GetString("PreviousAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveAppBarButton {
            get {
                return ResourceManager.GetString("SaveAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchAppBarButton {
            get {
                return ResourceManager.GetString("SearchAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the currently playing artist name to.
        /// </summary>
        public static string SettingsArtistTapAction {
            get {
                return ResourceManager.GetString("SettingsArtistTapAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open album page.
        /// </summary>
        public static string SettingsArtistTapOpenAlbumPage {
            get {
                return ResourceManager.GetString("SettingsArtistTapOpenAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open artist page.
        /// </summary>
        public static string SettingsArtistTapOpenArtistPage {
            get {
                return ResourceManager.GetString("SettingsArtistTapOpenArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended error reporting.
        /// </summary>
        public static string SettingsExtendedErrorReporting {
            get {
                return ResourceManager.GetString("SettingsExtendedErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staying connected to your library while the phone is locked will make resuming from the lock screen faster but may use more battery..
        /// </summary>
        public static string SettingsStayConnectedDescription {
            get {
                return ResourceManager.GetString("SettingsStayConnectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected under lock screen.
        /// </summary>
        public static string SettingsStayConnectedUnderLock {
            get {
                return ResourceManager.GetString("SettingsStayConnectedUnderLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will take effect the next time you start Remote..
        /// </summary>
        public static string SettingsTakeEffectNextRun {
            get {
                return ResourceManager.GetString("SettingsTakeEffectNextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
