//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komodex.WP7DACPRemote.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komodex.WP7DACPRemote.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Information.
        /// </summary>
        public static string AboutLibraryInformation {
            get {
                return ResourceManager.GetString("AboutLibraryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddAppBarButton {
            get {
                return ResourceManager.GetString("AddAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library.
        /// </summary>
        public static string AddLibraryButton {
            get {
                return ResourceManager.GetString("AddLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pair this device with a new library, download the Pairing Utility from our website:.
        /// </summary>
        public static string AddNewLibraryPageDescription {
            get {
                return ResourceManager.GetString("AddNewLibraryPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW LIBRARY.
        /// </summary>
        public static string AddNewLibraryPageTitle {
            get {
                return ResourceManager.GetString("AddNewLibraryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to airplay speakers.
        /// </summary>
        public static string AirPlaySpeakersMenuItem {
            get {
                return ResourceManager.GetString("AirPlaySpeakersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRPLAY SPEAKERS.
        /// </summary>
        public static string AirPlaySpeakersPageTitle {
            get {
                return ResourceManager.GetString("AirPlaySpeakersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        public static string AlbumPageTitle {
            get {
                return ResourceManager.GetString("AlbumPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string BrowseLibraryAppBarButton {
            get {
                return ResourceManager.GetString("BrowseLibraryAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse library.
        /// </summary>
        public static string BrowseLibraryButton {
            get {
                return ResourceManager.GetString("BrowseLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse library.
        /// </summary>
        public static string BrowseLibraryMenuItem {
            get {
                return ResourceManager.GetString("BrowseLibraryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelAppBarButton {
            get {
                return ResourceManager.GetString("CancelAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Library....
        /// </summary>
        public static string ChooseLibraryButton {
            get {
                return ResourceManager.GetString("ChooseLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose library.
        /// </summary>
        public static string ChooseLibraryMenuItem {
            get {
                return ResourceManager.GetString("ChooseLibraryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose library.
        /// </summary>
        public static string ChooseLibraryPageTitle {
            get {
                return ResourceManager.GetString("ChooseLibraryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Contact us] for support and feedback.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pair with iTunes or another compatible application for the first time, run the Pairing Utility on your computer.  This utility can be downloaded from our website at:.
        /// </summary>
        public static string FirstRunIntro1 {
            get {
                return ResourceManager.GetString("FirstRunIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When pairing has been completed, tap &quot;Add Library&quot; below to connect to your library..
        /// </summary>
        public static string FirstRunIntro2 {
            get {
                return ResourceManager.GetString("FirstRunIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be necessary for your phone to be connected to a Wi-fi network to continue..
        /// </summary>
        public static string FirstRunIntro3 {
            get {
                return ResourceManager.GetString("FirstRunIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow [@WP7Remote] on Twitter.
        /// </summary>
        public static string FollowOnTwitter {
            get {
                return ResourceManager.GetString("FollowOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone 7.
        /// </summary>
        public static string ForWP7 {
            get {
                return ResourceManager.GetString("ForWP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last connection attempt.
        /// </summary>
        public static string FromLastConnectionAttempt {
            get {
                return ResourceManager.GetString("FromLastConnectionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on music by:.
        /// </summary>
        public static string GeniusMixBasedOnMusicBy {
            get {
                return ResourceManager.GetString("GeniusMixBasedOnMusicBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genius mixes.
        /// </summary>
        public static string GeniusMixesListItem {
            get {
                return ResourceManager.GetString("GeniusMixesListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genius mixes.
        /// </summary>
        public static string GeniusMixesPageTitle {
            get {
                return ResourceManager.GetString("GeniusMixesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No albums were found for this genre..
        /// </summary>
        public static string GenreNoAlbumsFound {
            get {
                return ResourceManager.GetString("GenreNoAlbumsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artists were found for this genre..
        /// </summary>
        public static string GenreNoArtistsFound {
            get {
                return ResourceManager.GetString("GenreNoArtistsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs were found for this genre..
        /// </summary>
        public static string GenreNoSongsFound {
            get {
                return ResourceManager.GetString("GenreNoSongsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string LibraryAlbumsPivotItem {
            get {
                return ResourceManager.GetString("LibraryAlbumsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string LibraryArtistsPivotItem {
            get {
                return ResourceManager.GetString("LibraryArtistsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the library. Please make sure your phone is connected to the correct Wi-fi network and check the value entered in the hostname field..
        /// </summary>
        public static string LibraryConnectionErrorBody {
            get {
                return ResourceManager.GetString("LibraryConnectionErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string LibraryConnectionErrorTitle {
            get {
                return ResourceManager.GetString("LibraryConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please check your library and try again..
        /// </summary>
        public static string LibraryErrorBody {
            get {
                return ResourceManager.GetString("LibraryErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Error.
        /// </summary>
        public static string LibraryErrorTitle {
            get {
                return ResourceManager.GetString("LibraryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        public static string LibraryGenresPivotItem {
            get {
                return ResourceManager.GetString("LibraryGenresPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string LibraryHostname {
            get {
                return ResourceManager.GetString("LibraryHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No albums were found in your library..
        /// </summary>
        public static string LibraryNoAlbumsFound {
            get {
                return ResourceManager.GetString("LibraryNoAlbumsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artists were found in your library..
        /// </summary>
        public static string LibraryNoArtistsFound {
            get {
                return ResourceManager.GetString("LibraryNoArtistsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No genres were found in your library..
        /// </summary>
        public static string LibraryNoGenresFound {
            get {
                return ResourceManager.GetString("LibraryNoGenresFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlists were found in your library..
        /// </summary>
        public static string LibraryNoPlaylistsFound {
            get {
                return ResourceManager.GetString("LibraryNoPlaylistsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No podcasts were found in your library..
        /// </summary>
        public static string LibraryNoPodcastsFound {
            get {
                return ResourceManager.GetString("LibraryNoPodcastsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string LibraryPIN {
            get {
                return ResourceManager.GetString("LibraryPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the library. Please check the PIN and try again..
        /// </summary>
        public static string LibraryPINErrorBody {
            get {
                return ResourceManager.GetString("LibraryPINErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Error.
        /// </summary>
        public static string LibraryPINErrorTitle {
            get {
                return ResourceManager.GetString("LibraryPINErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlists.
        /// </summary>
        public static string LibraryPlaylistsPivotItem {
            get {
                return ResourceManager.GetString("LibraryPlaylistsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcasts.
        /// </summary>
        public static string LibraryPodcastsButton {
            get {
                return ResourceManager.GetString("LibraryPodcastsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string LibrarySongsPivotItem {
            get {
                return ResourceManager.GetString("LibrarySongsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to your library. Please disconnect the USB cable between your phone and computer and try again..
        /// </summary>
        public static string LibraryUSBErrorBody {
            get {
                return ResourceManager.GetString("LibraryUSBErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connection Error.
        /// </summary>
        public static string LibraryUSBErrorTitle {
            get {
                return ResourceManager.GetString("LibraryUSBErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application currently requires iTunes version 10.1 or later. Please upgrade to the latest version of iTunes to continue..
        /// </summary>
        public static string LibraryVersionErrorBody {
            get {
                return ResourceManager.GetString("LibraryVersionErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Version Error.
        /// </summary>
        public static string LibraryVersionErrorTitle {
            get {
                return ResourceManager.GetString("LibraryVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos.
        /// </summary>
        public static string LibraryVideosButton {
            get {
                return ResourceManager.GetString("LibraryVideosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure your phone is connected to a Wi-fi network and try again..
        /// </summary>
        public static string LibraryWifiErrorBody {
            get {
                return ResourceManager.GetString("LibraryWifiErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-fi Connection Error.
        /// </summary>
        public static string LibraryWifiErrorTitle {
            get {
                return ResourceManager.GetString("LibraryWifiErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASTER VOLUME.
        /// </summary>
        public static string MasterVolume {
            get {
                return ResourceManager.GetString("MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string MoreAppBarButton {
            get {
                return ResourceManager.GetString("MoreAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        public static string MultipleItems {
            get {
                return ResourceManager.GetString("MultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string NextAppBarButton {
            get {
                return ResourceManager.GetString("NextAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingAppBarButton {
            get {
                return ResourceManager.GetString("NowPlayingAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingButton {
            get {
                return ResourceManager.GetString("NowPlayingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item.
        /// </summary>
        public static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLISTS.
        /// </summary>
        public static string PlaylistPageTitle {
            get {
                return ResourceManager.GetString("PlaylistPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play/pause.
        /// </summary>
        public static string PlayPauseAppBarButton {
            get {
                return ResourceManager.GetString("PlayPauseAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODCASTS.
        /// </summary>
        public static string PodcastPageTitle {
            get {
                return ResourceManager.GetString("PodcastPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcasts.
        /// </summary>
        public static string PodcastsPageTitle {
            get {
                return ResourceManager.GetString("PodcastsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string PreviousAppBarButton {
            get {
                return ResourceManager.GetString("PreviousAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveAppBarButton {
            get {
                return ResourceManager.GetString("SaveAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchAppBarButton {
            get {
                return ResourceManager.GetString("SearchAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchMenuItem {
            get {
                return ResourceManager.GetString("SearchMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH LIBRARY.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MEDIA TYPE.
        /// </summary>
        public static string SelectMediaPageTitle {
            get {
                return ResourceManager.GetString("SelectMediaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the currently playing artist name to.
        /// </summary>
        public static string SettingsArtistTapAction {
            get {
                return ResourceManager.GetString("SettingsArtistTapAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open album page.
        /// </summary>
        public static string SettingsArtistTapOpenAlbumPage {
            get {
                return ResourceManager.GetString("SettingsArtistTapOpenAlbumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open artist page.
        /// </summary>
        public static string SettingsArtistTapOpenArtistPage {
            get {
                return ResourceManager.GetString("SettingsArtistTapOpenArtistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended error reporting.
        /// </summary>
        public static string SettingsExtendedErrorReporting {
            get {
                return ResourceManager.GetString("SettingsExtendedErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staying connected to your library while the phone is locked will make resuming from the lock screen faster but may use more battery..
        /// </summary>
        public static string SettingsStayConnectedDescription {
            get {
                return ResourceManager.GetString("SettingsStayConnectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected under lock screen.
        /// </summary>
        public static string SettingsStayConnectedUnderLock {
            get {
                return ResourceManager.GetString("SettingsStayConnectedUnderLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will take effect the next time you start Remote..
        /// </summary>
        public static string SettingsTakeEffectNextRun {
            get {
                return ResourceManager.GetString("SettingsTakeEffectNextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuffle album.
        /// </summary>
        public static string ShuffleAlbumButton {
            get {
                return ResourceManager.GetString("ShuffleAlbumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuffle all.
        /// </summary>
        public static string ShuffleAllButton {
            get {
                return ResourceManager.GetString("ShuffleAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuffle all songs.
        /// </summary>
        public static string ShuffleAllSongsMenuItem {
            get {
                return ResourceManager.GetString("ShuffleAllSongsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Library.
        /// </summary>
        public static string StatusConnectingToLibrary {
            get {
                return ResourceManager.GetString("StatusConnectingToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap &quot;Choose Library&quot; to select or add a new library..
        /// </summary>
        public static string StatusTapChooseLibrary {
            get {
                return ResourceManager.GetString("StatusTapChooseLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days left.
        /// </summary>
        public static string TrialBannerContentPlural {
            get {
                return ResourceManager.GetString("TrialBannerContentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day left.
        /// </summary>
        public static string TrialBannerContentSingular {
            get {
                return ResourceManager.GetString("TrialBannerContentSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Mode.
        /// </summary>
        public static string TrialBannerHeader {
            get {
                return ResourceManager.GetString("TrialBannerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string TrialReminderButtonBuy {
            get {
                return ResourceManager.GetString("TrialReminderButtonBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string TrialReminderButtonCancel {
            get {
                return ResourceManager.GetString("TrialReminderButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently running the trial version of Remote. There are {0} days left in your trial..
        /// </summary>
        public static string TrialReminderContentPlural {
            get {
                return ResourceManager.GetString("TrialReminderContentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently running the trial version of Remote. There is 1 day left in your trial..
        /// </summary>
        public static string TrialReminderContentSingular {
            get {
                return ResourceManager.GetString("TrialReminderContentSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has expired..
        /// </summary>
        public static string TrialReminderExpiredContent {
            get {
                return ResourceManager.GetString("TrialReminderExpiredContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial expired.
        /// </summary>
        public static string TrialReminderExpiredHeader {
            get {
                return ResourceManager.GetString("TrialReminderExpiredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial mode.
        /// </summary>
        public static string TrialReminderHeader {
            get {
                return ResourceManager.GetString("TrialReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to upgrade to the full version of Remote?.
        /// </summary>
        public static string TrialReminderUpgradeToFull {
            get {
                return ResourceManager.GetString("TrialReminderUpgradeToFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade to full version.
        /// </summary>
        public static string TrialUpgradeToFullMenuItem {
            get {
                return ResourceManager.GetString("TrialUpgradeToFullMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies.
        /// </summary>
        public static string VideosMoviesPivotItem {
            get {
                return ResourceManager.GetString("VideosMoviesPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies were found in your library..
        /// </summary>
        public static string VideosNoMoviesFound {
            get {
                return ResourceManager.GetString("VideosNoMoviesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TV shows were found in your library..
        /// </summary>
        public static string VideosNoTVShowsFound {
            get {
                return ResourceManager.GetString("VideosNoTVShowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv shows.
        /// </summary>
        public static string VideosTVShowsPivotItem {
            get {
                return ResourceManager.GetString("VideosTVShowsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Wi-Fi connection....
        /// </summary>
        public static string WaitingForWiFiConnection {
            get {
                return ResourceManager.GetString("WaitingForWiFiConnection", resourceCulture);
            }
        }
    }
}
