//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komodex.WP7DACPRemote.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Komodex.WP7DACPRemote.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Information.
        /// </summary>
        public static string AboutLibraryInformation {
            get {
                return ResourceManager.GetString("AboutLibraryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library.
        /// </summary>
        public static string AddLibraryButton {
            get {
                return ResourceManager.GetString("AddLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse library.
        /// </summary>
        public static string BrowseLibraryButton {
            get {
                return ResourceManager.GetString("BrowseLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Contact us] for support and feedback.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pair with iTunes or another compatible application for the first time, run the Pairing Utility on your computer.  This utility can be downloaded from our website at:.
        /// </summary>
        public static string FirstRunIntro1 {
            get {
                return ResourceManager.GetString("FirstRunIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When pairing has been completed, tap &quot;Add Library&quot; below to connect to your library..
        /// </summary>
        public static string FirstRunIntro2 {
            get {
                return ResourceManager.GetString("FirstRunIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be necessary for your phone to be connected to a Wi-fi network to continue..
        /// </summary>
        public static string FirstRunIntro3 {
            get {
                return ResourceManager.GetString("FirstRunIntro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow [@WP7Remote] on Twitter.
        /// </summary>
        public static string FollowOnTwitter {
            get {
                return ResourceManager.GetString("FollowOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone 7.
        /// </summary>
        public static string ForWP7 {
            get {
                return ResourceManager.GetString("ForWP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last connection attempt.
        /// </summary>
        public static string FromLastConnectionAttempt {
            get {
                return ResourceManager.GetString("FromLastConnectionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingButton {
            get {
                return ResourceManager.GetString("NowPlayingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
